// internal/report/markdown/markdown.go
package markdown

import (
	"fmt"
	"io"
	"sort"

	"github.com/clementlevoux/benchbuddy/internal/runresult"
)

// Render writes a Markdown report to w.
func Render(w io.Writer, r runresult.Report) error {
	fmt.Fprintf(w, "# BenchBuddy Report\n\n")
	fmt.Fprintf(w, "**Run:** %s  \n", r.Meta.RunID)
	fmt.Fprintf(w, "**Profile:** %s  \n", r.Meta.Profile)
	fmt.Fprintf(w, "**Namespace:** %s  \n", r.Meta.Namespace)
	fmt.Fprintf(w, "**Cluster:** k8s=%s  cni=%s  nodes=%d  \n", r.Meta.K8sVersion, r.Meta.CNI, r.Meta.NodeCount)
	fmt.Fprintf(w, "**Duration:** %s  \n", r.Meta.Duration)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "---")
	fmt.Fprintln(w)

	fmt.Fprintln(w, "## Results")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Bench | Subject | Status | Key Metrics |")
	fmt.Fprintln(w, "|-------|---------|--------|-------------|")
	for _, res := range r.Results {
		fmt.Fprintf(w, "| %s | %s | %s | %s |\n",
			res.BenchName, res.Subject, res.Status, formatMetrics(res.Metrics))
	}
	fmt.Fprintln(w)

	if len(r.Findings) == 0 {
		fmt.Fprintln(w, "*Generated by BenchBuddy*")
		return nil
	}

	fmt.Fprintln(w, "---")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "## Findings")
	for _, f := range r.Findings {
		fmt.Fprintln(w)
		fmt.Fprintf(w, "### [%s] %s: %s\n\n", f.Severity, f.Category, f.Title)
		fmt.Fprintf(w, "%s\n", f.Detail)
		if len(f.Fix) > 0 {
			fmt.Fprintln(w)
			fmt.Fprintln(w, "**Suggested fixes:**")
			for _, fix := range f.Fix {
				fmt.Fprintf(w, "- %s\n", fix)
			}
		}
		if len(f.Refs) > 0 {
			fmt.Fprintln(w)
			fmt.Fprintln(w, "**References:**")
			for _, ref := range f.Refs {
				fmt.Fprintf(w, "- %s\n", ref)
			}
		}
	}
	fmt.Fprintln(w)
	fmt.Fprintln(w, "---")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "*Generated by BenchBuddy*")
	return nil
}

func formatMetrics(m map[string]runresult.Metric) string {
	if len(m) == 0 {
		return ""
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	out := ""
	for i, k := range keys {
		if i > 0 {
			out += " "
		}
		out += fmt.Sprintf("%s=%.2f %s", k, m[k].Value, m[k].Unit)
	}
	return out
}
